# Generated by Django 5.2.3 on 2026-03-11 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_account_id', models.IntegerField(unique=True)),
                ('github_user_json', models.JSONField()),
                ('github_sponsors_profile_url', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsoredissues.githubappinstallation')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='sponsoredissues.githubrepo')),
            ],
            options={
                'verbose_name': 'GitHub Issue',
                'verbose_name_plural': 'GitHub Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='githubappinstallation',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsoredissues.maintainer'),
        ),
        migrations.CreateModel(
            name='IssueSponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cents_usd', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_amounts', to='sponsoredissues.githubissue')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_amounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sponsor Amount',
                'verbose_name_plural': 'Sponsor Amounts',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cents_usd__gt', 0)), name='cents_usd_positive')],
            },
        ),
    ]
