# Generated by Django 5.2.3 on 2025-09-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='paypal_order_id',
        ),
    ]
