# Generated by Django 5.2.3 on 2025-09-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0004_remove_donation_paypal_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_amounts', to=settings.AUTH_USER_MODEL)),
                ('target_github_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_amounts', to='sponsoredissues.githubissue')),
            ],
            options={
                'verbose_name': 'Sponsor Amount',
                'verbose_name_plural': 'Sponsor Amounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
