# Generated by Django 5.2.3 on 2025-09-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0005_sponsoramount_delete_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsoramount',
            old_name='sponsor_user_id',
            new_name='sponsor_user',
        ),
    ]
