# Generated by Django 5.2.3 on 2025-09-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0006_rename_sponsor_user_id_sponsoramount_sponsor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsoramount',
            old_name='amount',
            new_name='cents_usd',
        ),
    ]
