# Generated by Django 5.2.3 on 2025-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0007_rename_amount_sponsoramount_cents_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoramount',
            name='cents_usd',
            field=models.IntegerField(),
        ),
    ]
