# Generated by Django 5.2.3 on 2025-11-25 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0008_alter_sponsoramount_cents_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sponsoramount',
            constraint=models.CheckConstraint(condition=models.Q(('cents_usd__gt', 0)), name='cents_usd_positive'),
        ),
    ]
