# Generated by Django 5.2.3 on 2026-01-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0010_githubrepo_githubissue_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('url', models.URLField(max_length=500, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='app_installation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsoredissues.githubappinstallation'),
        ),
    ]
