# Generated by Django 5.2.3 on 2026-01-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0012_githubrepo_init_app_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='app_installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsoredissues.githubappinstallation'),
        ),
    ]
