# Generated by Django 5.2.3 on 2026-01-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0013_alter_githubrepo_app_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoramount',
            name='target_github_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_amounts', to='sponsoredissues.githubissue'),
        ),
    ]
