# Generated by Django 5.2.3 on 2026-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0014_alter_sponsoramount_target_github_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubappinstallation',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
