# Generated by Django 5.2.3 on 2026-02-25 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0016_githubappinstallation_data_set_null_false'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SponsorAmount',
            new_name='IssueSponsorship',
        ),
    ]
