# Generated by Django 5.2.3 on 2026-02-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0017_rename_sponsoramount_issuesponsorship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuesponsorship',
            old_name='sponsor_user',
            new_name='sponsor',
        ),
    ]
