# Generated by Django 5.2.3 on 2026-02-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0018_rename_sponsor_user_issuesponsorship_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuesponsorship',
            old_name='target_github_issue',
            new_name='issue',
        ),
    ]
