# Generated by Django 5.2.3 on 2026-02-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0019_rename_target_github_issue_issuesponsorship_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_account_id', models.IntegerField(unique=True)),
                ('github_user_json', models.JSONField()),
                ('github_sponsors_profile_url', models.URLField(max_length=500, null=True)),
            ],
        ),
    ]
