# Generated by Django 5.2.3 on 2026-02-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoredissues', '0020_maintainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubappinstallation',
            name='maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsoredissues.maintainer'),
        ),
    ]
