# Generated by Django 5.2.3 on 2025-08-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugpile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubissue',
            options={'ordering': ['-created_at'], 'verbose_name': 'GitHub Issue', 'verbose_name_plural': 'GitHub Issues'},
        ),
    ]
