import logging

from celery.signals import setup_logging

# Configure Celery to use the same logging configuration as Django.
#
# By default, Celery uses its own logging configuration which is
# completely independent from Django, and only log statements that are
# generated by Celery's loggers appear in the Celery worker log.
# This makes troubleshooting and debugging unnecessarily difficult,
# because most of the logging messages from the lower-level methods
# (e.g. `github_api` in `github_api.py`) are omitted.
#
# Using the configuration below, I'm able to see logging messages from
# *all* of my code, not just the log messages that are generated by
# Celery-specific code. For example, it allows me to enable detailed
# logging of HTTP requests/responses if I want to.
#
# One important downside of configuring Celery to share Django's
# logging configuration is that the log statements no longer include
# the Celery task name/id by default. That is extremely important
# information for debugging, because the Celery worker log typically
# mixes log statements from multiple Celery tasks running in parallel,
# and it is impossible to untangle the messages unless the task
# name/id is included on each line. I solve that issue by using the
# custom `LoggingFormatter` class below.
@setup_logging.connect
def config_loggers(*args, **kwargs):
    "Configure Celery to use Django's logging config."
    from django.conf import settings
    from logging.config import dictConfig
    dictConfig(settings.LOGGING)

class LoggingFormatter(logging.Formatter):
    """
    Custom logging formatter that includes Celery task name and ID
    when log output is generated in the context of a Celery task, or
    omits them otherwise.

    Based on: https://stackoverflow.com/a/14859558
    """
    def __init__(self, *args, **kwargs):
        # Specify default logging format, for log messages that are not
        # generated in the context of a Celery task.
        super().__init__(
            fmt='[%(asctime)s] [%(levelname)s] %(message)s',
            datefmt='%d/%b/%Y %H:%M:%S', # same as Django's default time format
            style='%')

    def format(self, record):
        # Based on: https://stackoverflow.com/a/14859558
        from sponsoredissues.celery import app as celery_app
        fmt_orig = self._style._fmt # save original log format
        task = celery_app.current_worker_task
        if task and task.request:
            self._style._fmt = f'[%(asctime)s] [{task.name}:{task.request.id}] [%(levelname)s] %(message)s'
        log_message = super().format(record)
        self._style._fmt = fmt_orig # restore original log format
        return log_message

class PrefixLoggerAdapter(logging.LoggerAdapter):
    """
    Create a wrapper logger that adds a custom prefix string to all
    log messages.
    """
    def process(self, msg, kwargs):
        assert self.extra
        assert 'prefix' in self.extra
        return f'{self.extra["prefix"]}{msg}', kwargs