"""
Django settings for sponsoredissues project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.core.management.utils import get_random_secret_key
from pathlib import Path
import dj_database_url
import os

# Helper functions for reading environment variables.
#
# I previously used the `django-environ` package for this, but
# I was not impressed by the quality of that library.In
# particular, the following bug convinced me that it
# would be better to just write my own code:
#
# https://github.com/joke2k/django-environ/issues/284

def env_list(env_var_name, default=None, required=True):
    """
    Read and parse an environment variable as a comma-separated list.
    """
    if default and not type(default) is list:
        raise RuntimeError(f'default value for `{env_var_name}` must be `None` or list')
    string_value = os.getenv(env_var_name)
    if string_value:
        items = string_value.split(',')
        list_value = [ item.strip() for item in items ]
        return list_value
    elif default != None:
        return default
    elif required:
        raise RuntimeError(f'required environment variable not set: `{env_var_name}`')
    else:
        return

def env_str(env_var_name, default=None, required=True):
    """
    Return the value of an environment variable as a string.
    """
    if default and not type(default) is str:
        raise RuntimeError(f'default value for `{env_var_name}` must `None` or string')
    string_value = os.getenv(env_var_name, default)
    if required and not string_value:
        raise RuntimeError(f'required environment variable not set: {env_var_name}')
    return string_value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_str('DJANGO_SECRET_KEY', default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'DJANGO_DEBUG' in os.environ

# `ALLOWED_HOSTS` is a security measure to block "HTTP Host header
# attacks". For further info, see:
# https://docs.djangoproject.com/en/5.2/ref/settings/#allowed-hosts
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sponsoredissues',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'sponsoredissues.middleware.github_autorefresh_token',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'APP': {
            'client_id': env_str('GITHUB_CLIENT_ID'),
            'secret': env_str('GITHUB_CLIENT_SECRET'),
        }
    }
}

# GitHub App configuration for API access
GITHUB_APP_ID = env_str('GITHUB_APP_ID')
GITHUB_APP_PRIVATE_KEY = env_str('GITHUB_APP_PRIVATE_KEY')

# For authenticating webhook notifications from GitHub
GITHUB_WEBHOOK_SECRET = env_str('GITHUB_WEBHOOK_SECRET')

# Comma separated list of GitHub usernames that are allowed to "Sign
# in with GitHub".
#
# Setting `ALLOWED_GITHUB_USERS` is optional. If the variable is not
# set, any GitHub user will be allowed to log in.
#
# Users that are not allowed to log in will see the custom message
# defined in GITHUB_LOGIN_DISABLED_MESSAGE.
#
# Example value:
# ALLOWED_GITHUB_USERS=user1,user2,user3
ALLOWED_GITHUB_USERS = env_list('ALLOWED_GITHUB_USERS', required=False)

# Custom message shown to users who are not in the whitelist
GITHUB_LOGIN_DISABLED_MESSAGE = env_str(
    'GITHUB_LOGIN_DISABLED_MESSAGE',
    default='Sorry, logins on sponsoredissues.org are currently disabled, because the site is still under development. Please come back in a few weeks!'
)

# Disable login with local Django accounts. Only allow "Login with GitHub".
SOCIALACCOUNT_ONLY = True
ACCOUNT_EMAIL_VERIFICATION = "none" # required for `SOCIALACCOUNT_ONLY = True`

# Custom adapter to restrict GitHub logins during development
SOCIALACCOUNT_ADAPTER = 'sponsoredissues.adapters.GitHubAccountAdapter'

# Save user's OAuth access token and refresh token to the database.
#
# We need the access token so that we can issue GraphQL queries on
# behalf of the logged-in user, in order to calculate the total amount
# donated to particular developers. Many details about sponsorships
# (e.g. dollar amounts) are only accessible to the sponsor (donor) and
# maintainer (donee).
SOCIALACCOUNT_STORE_TOKENS = True

ROOT_URLCONF = 'sponsoredissues.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'sponsoredissues' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sponsoredissues.wsgi.application'


# Database settings.
#
# The `dj-database-url` package [1] reads the database connection URL
# from the `DATABASE_URL` environment variable. If `DATABASE_URL` is
# not set, we fallback to using sqlite3 with a `db.sqlite3` file in
# the project root directory. (Django will automatically create the
# `db.sqlite3` file if it doesn't exist.)
#
# Without the `dj-database-url` package, I would need to specify the
# database connection parameters using separate
# `NAME`/`USER`/`PASSWORD`/`HOST`/`PORT` variables, which is rather
# tedious and error-prone.
#
# [1]: https://pypi.org/project/dj-database-url

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    ),
}

# Cache configuration
# Using database backend for persistent caching across server restarts
# Run `python manage.py createcachetable` to create the cache table
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration

if DEBUG:
    LOG_LEVEL = "DEBUG"
else:
    LOG_LEVEL = "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "sponsoredissues.formatter": {
            "class": "sponsoredissues.logging.LoggingFormatter",
        },
    },
    "handlers": {
        "sponsoredissues.handler": {
            "class": "logging.StreamHandler",
            "formatter": "sponsoredissues.formatter",
        },
    },
    "root": {
        "handlers": ["sponsoredissues.handler"],
        "level": LOG_LEVEL,
    },
}

# Redis connection URL.
#
# For local Redis on standard port, use `redis://localhost`.
#
# Redis is required for two purposes:
#
# (1) We use Redis as the message queue for Celery background jobs
# (see `CELERY_BROKER_URL` below).
#
# (2) We use Redis to implement distributed locks in
# `sponsoredissues/tasks.py` (via `redis-py` package).  Distributed
# locks need to be used to ensure that two Celery tasks don't try to
# modify the same GitHub App installation in the database
# simultaneously.

REDIS_URL = env_str('REDIS_URL')

# Celery settings

CELERY_BROKER_URL = REDIS_URL
